name: Generate new release changelog
on:
  repository_dispatch:
    types: generate-pr
  schedule:
    - cron: '0 2 * * *'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Update dependencies
        run: |
          npm install -g standard-version
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: chore
          assignees: morgante
          reviewers: morgante
          title: 'Release new version'
          branch: create-pull-request/patch-gcloud-version
          branch-suffix: none
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
